services:
  - type: web
    name: riverdash
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: VITE_GH_PAGES
        value: 'false'
    plan: free
